// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNPVyF6LMc813hOL4FoRO_P6xhW6P7SHQ',
    appId: '1:270477898823:web:3c2d5350c7d9d658b62d62',
    messagingSenderId: '270477898823',
    projectId: 'crudtutorial-35129',
    authDomain: 'crudtutorial-35129.firebaseapp.com',
    storageBucket: 'crudtutorial-35129.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqu4MTfJD6YyhU4sDYgQLCTXOE7fU8BvM',
    appId: '1:270477898823:android:82bae841e40c5556b62d62',
    messagingSenderId: '270477898823',
    projectId: 'crudtutorial-35129',
    storageBucket: 'crudtutorial-35129.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNy5DiRHK2ZNVZaqRxbyDZcCYxxbm0184',
    appId: '1:270477898823:ios:600f77ffa7674232b62d62',
    messagingSenderId: '270477898823',
    projectId: 'crudtutorial-35129',
    storageBucket: 'crudtutorial-35129.appspot.com',
    iosBundleId: 'com.example.firebaseTutorial',
  );
}
